# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\"y\n\x0cHelloRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x14\n\x0ctimeAtClient\x18\x03 \x01(\t\x12\x16\n\x0epastWindowData\x18\x04 \x01(\t\x12\x16\n\x0esequenceNumber\x18\x05 \x01(\t\"H\n\nHelloReply\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x12\n\nserverTime\x18\x02 \x01(\t\x12\x13\n\x0brequestTime\x18\x03 \x01(\t23\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=20
  _HELLOREQUEST._serialized_end=141
  _HELLOREPLY._serialized_start=143
  _HELLOREPLY._serialized_end=215
  _GREETER._serialized_start=217
  _GREETER._serialized_end=268
# @@protoc_insertion_point(module_scope)
