# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10helloworld.proto\"\x8a\x01\n\x0cHelloRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x14\n\x0ctimeAtClient\x18\x03 \x01(\t\x12\x16\n\x0epastWindowData\x18\x04 \x01(\t\x12\x16\n\x0esequenceNumber\x18\x05 \x01(\t\x12\x0f\n\x07history\x18\x06 \x01(\t\"H\n\nHelloReply\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x12\n\nserverTime\x18\x02 \x01(\t\x12\x13\n\x0brequestTime\x18\x03 \x01(\t\"z\n\x13HelloRequestReplica\x12\x11\n\treplicaId\x18\x01 \x01(\t\x12\x11\n\trequestId\x18\x02 \x01(\t\x12\x0f\n\x07history\x18\x03 \x01(\t\x12\x16\n\x0epastWindowData\x18\x04 \x01(\t\x12\x14\n\x0ctimeAtSender\x18\x05 \x01(\t\">\n\x11HelloReplyReplica\x12\x11\n\trequestId\x18\x01 \x01(\t\x12\x16\n\x0etimeAtReceiver\x18\x02 \x01(\t2r\n\x07Greeter\x12(\n\x08SayHello\x12\r.HelloRequest\x1a\x0b.HelloReply\"\x00\x12=\n\x0fSayHelloReplica\x12\x14.HelloRequestReplica\x1a\x12.HelloReplyReplica\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helloworld_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOREQUEST._serialized_start=21
  _HELLOREQUEST._serialized_end=159
  _HELLOREPLY._serialized_start=161
  _HELLOREPLY._serialized_end=233
  _HELLOREQUESTREPLICA._serialized_start=235
  _HELLOREQUESTREPLICA._serialized_end=357
  _HELLOREPLYREPLICA._serialized_start=359
  _HELLOREPLYREPLICA._serialized_end=421
  _GREETER._serialized_start=423
  _GREETER._serialized_end=537
# @@protoc_insertion_point(module_scope)
